2019-10-14T15:41:42.7463211+01:00;VSTestExecutionThread;Info;SpecFlow+Runner execution started
2019-10-14T15:41:42.7463211+01:00;VSTestExecutionThread;Info;SpecFlow+Runner 3.0.391 in Framework clr40 in x86 mode execution started
2019-10-14T15:41:42.7463211+01:00;VSTestExecutionThread;Info;TestAdapter Location: C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\packages\SpecRun.Runner.3.0.391\tools\net45\TechTalk.SpecRun.VisualStudio.TestAdapter.dll
2019-10-14T15:41:42.8183214+01:00;VSTestExecutionThread;Info;SpecRun: running tests in C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\CSharpSpecFlowSelenium\bin\Debug\CSharpSpecFlowSelenium.dll
2019-10-14T15:41:42.8183214+01:00;VSTestExecutionThread;Info;Output folder configured to "C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\TestResults" (default)
2019-10-14T15:41:42.8183214+01:00;VSTestExecutionThread;Info;Profile: 
2019-10-14T15:41:42.8523208+01:00;VSTestExecutionThread;Info;Log file path: C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\TestResults\Unnamed project__2019-10-14T154142.log
2019-10-14T15:41:42.8723228+01:00;VSTestExecutionThread;Info;SpecFlow+Runner Evaluation Mode: Please purchase at http://www.specflow.org/plus to remove test execution delay.
2019-10-14T15:41:42.8843219+01:00;Thread#14;Info;Checking license
2019-10-14T15:41:42.9173232+01:00;Thread#14;Info;Evaluation mode: test execution starts in 14 seconds... (this delay is removed in the registered version)
2019-10-14T15:41:56.9184072+01:00;Thread#14;Info;Evaluation delay finished.
2019-10-14T15:41:56.9303921+01:00;Thread#14;Info;License check completed
2019-10-14T15:41:56.9313926+01:00;Thread#14;Info;starting test run
2019-10-14T15:41:56.9514001+01:00;Thread#14;Info;Discovering target: Default
2019-10-14T15:41:56.9514001+01:00;Thread#14;Info;Discovering tests from assembly: C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\CSharpSpecFlowSelenium\bin\Debug\CSharpSpecFlowSelenium.dll
2019-10-14T15:41:57.8433931+01:00:Appdomain Disposed
2019-10-14T15:41:57.8433931+01:00;Thread#14;Info;Discovered tests from assembly: C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\CSharpSpecFlowSelenium\bin\Debug\CSharpSpecFlowSelenium.dll
2019-10-14T15:41:57.8443935+01:00:Test Suite Dump
2019-10-14T15:41:57.8473967+01:00:#0: Unnamed project/ - 
2019-10-14T15:41:57.8473967+01:00:#1: Default - 
2019-10-14T15:41:57.8473967+01:00:#2: CSharpSpecFlowSelenium - 
2019-10-14T15:41:57.8473967+01:00:#3: BBCLogin1 - 
2019-10-14T15:41:57.9043925+01:00:#4: Invalid password - TestAssembly:CSharpSpecFlowSelenium/Feature:BBCLogin1/Scenario:Invalid+password
2019-10-14T15:41:57.9043925+01:00:#5: Valid password - TestAssembly:CSharpSpecFlowSelenium/Feature:BBCLogin1/Scenario:Valid+password
2019-10-14T15:41:57.9043925+01:00:End: Test Suite Dump
2019-10-14T15:41:57.9433899+01:00:Thread#0:Scheduler: get next test for thread 0
2019-10-14T15:41:57.9463905+01:00:Thread#:Scheduler: testitem #4 from normal test queue 
2019-10-14T15:41:57.9463905+01:00:Thread#0:Scheduler: considering testitem #4 for thread 0
2019-10-14T15:41:57.9533937+01:00:Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
2019-10-14T15:41:57.9533937+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
2019-10-14T15:41:57.9533937+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
2019-10-14T15:41:57.9533937+01:00:Thread#0:Scheduler: using testitem #4 for thread 0
2019-10-14T15:41:57.9583941+01:00:Thread#0:Scheduler: Test #4 is scheduled for thread
2019-10-14T15:41:57.9603900+01:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2019-10-14T15:41:57.9643898+01:00:Thread #0: creating new test thread executor for CSharpSpecFlowSelenium, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
2019-10-14T15:41:57.9673915+01:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-10-14T15:41:57.9683916+01:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-10-14T15:41:57.9703915+01:00:Thread #0: using TechTalk.SpecRun.Framework.Execution.InProcess.InProcAppDomainTestAssemblyExecutorHost to execute tests
2019-10-14T15:41:58.1353922+01:00:Thread#0: Test #4/0 is started on thread #0
2019-10-14T15:41:58.4783959+01:00:Thread#0:T:-> Loading plugin C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\CSharpSpecFlowSelenium\bin\Debug\SpecRun.Runtime.SpecFlowPlugin.dll
2019-10-14T15:41:58.4903955+01:00:Thread#0:T:-> Using default config
2019-10-14T15:41:58.5803903+01:00:Thread#0:B:Given I am on the login page
2019-10-14T15:41:58.7213910+01:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-10-14T15:41:58.7233906+01:00:Thread#0:B:And I have enter a valid username
2019-10-14T15:41:58.7233906+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.7233906+01:00:Thread#0:B:And I have entered a invalid password
2019-10-14T15:41:58.7243926+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.7243926+01:00:Thread#0:B:When I press login
2019-10-14T15:41:58.7243926+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.7253918+01:00:Thread#0:B:Then I should see the appropriate error
2019-10-14T15:41:58.7263932+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8113948+01:00:Thread#0:TestItem#4:Scheduler: reschedule tests for testitem #4
2019-10-14T15:41:58.8133933+01:00:Thread#0:Scheduler: get next test for thread 0
2019-10-14T15:41:58.8133933+01:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #4
2019-10-14T15:41:58.8133933+01:00:Thread#0:Scheduler: considering testitem #4 for thread 0
2019-10-14T15:41:58.8133933+01:00:Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
2019-10-14T15:41:58.8133933+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
2019-10-14T15:41:58.8133933+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
2019-10-14T15:41:58.8133933+01:00:Thread#0:Scheduler: using testitem #4 for thread 0
2019-10-14T15:41:58.8133933+01:00:Thread#0:Scheduler: Test #4 is scheduled for thread
2019-10-14T15:41:58.8133933+01:00:Thread#0:Scheduler: with testItemExecutionIndex 1
2019-10-14T15:41:58.8473948+01:00:Thread#0: Test #4/0 is finished on thread #0 as Failed within 0.7110082 seconds
2019-10-14T15:41:58.8493933+01:00:Thread#0: Test #4/1 is started on thread #0
2019-10-14T15:41:58.8503937+01:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-10-14T15:41:58.8543929+01:00:Thread#0:B:Given I am on the login page
2019-10-14T15:41:58.8584104+01:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-10-14T15:41:58.8584104+01:00:Thread#0:B:And I have enter a valid username
2019-10-14T15:41:58.8593957+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8593957+01:00:Thread#0:B:And I have entered a invalid password
2019-10-14T15:41:58.8593957+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8593957+01:00:Thread#0:B:When I press login
2019-10-14T15:41:58.8593957+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8593957+01:00:Thread#0:B:Then I should see the appropriate error
2019-10-14T15:41:58.8604194+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8613957+01:00:Thread#0:Scheduler: get next test for thread 0
2019-10-14T15:41:58.8613957+01:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #4
2019-10-14T15:41:58.8613957+01:00:Thread#0:Scheduler: considering testitem #4 for thread 0
2019-10-14T15:41:58.8613957+01:00:Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
2019-10-14T15:41:58.8613957+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
2019-10-14T15:41:58.8613957+01:00:Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
2019-10-14T15:41:58.8613957+01:00:Thread#0:Scheduler: using testitem #4 for thread 0
2019-10-14T15:41:58.8613957+01:00:Thread#0:Scheduler: Test #4 is scheduled for thread
2019-10-14T15:41:58.8623955+01:00:Thread#0:Scheduler: with testItemExecutionIndex 2
2019-10-14T15:41:58.8654005+01:00:Thread#0: Test #4/1 is finished on thread #0 as Failed within 0.0160072 seconds
2019-10-14T15:41:58.8663965+01:00:Thread#0: Test #4/2 is started on thread #0
2019-10-14T15:41:58.8663965+01:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-10-14T15:41:58.8663965+01:00:Thread#0:B:Given I am on the login page
2019-10-14T15:41:58.8773944+01:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-10-14T15:41:58.8783941+01:00:Thread#0:B:And I have enter a valid username
2019-10-14T15:41:58.8783941+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8793962+01:00:Thread#0:B:And I have entered a invalid password
2019-10-14T15:41:58.8804165+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8804165+01:00:Thread#0:B:When I press login
2019-10-14T15:41:58.8813984+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8823944+01:00:Thread#0:B:Then I should see the appropriate error
2019-10-14T15:41:58.8823944+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8833958+01:00:Thread#0:Scheduler: get next test for thread 0
2019-10-14T15:41:58.8833958+01:00:Thread#:Scheduler: testitem #5 from normal test queue 
2019-10-14T15:41:58.8833958+01:00:Thread#0:Scheduler: considering testitem #5 for thread 0
2019-10-14T15:41:58.8833958+01:00:Thread#0:TestItem#5:testItemMatchesCurrentTestThread:UnSpecific
2019-10-14T15:41:58.8833958+01:00:Thread#0:TestItem#5:runsOnOneOtherThreadSpecific:False
2019-10-14T15:41:58.8833958+01:00:Thread#0:TestItem#5:runsOnOneOtherThreadUnspecific:False
2019-10-14T15:41:58.8833958+01:00:Thread#0:Scheduler: using testitem #5 for thread 0
2019-10-14T15:41:58.8833958+01:00:Thread#0:Scheduler: Test #5 is scheduled for thread
2019-10-14T15:41:58.8833958+01:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2019-10-14T15:41:58.8873954+01:00:Thread#0: Test #4/2 is finished on thread #0 as Failed within 0.0209989 seconds
2019-10-14T15:41:58.8873954+01:00:Thread#0: Test #5/0 is started on thread #0
2019-10-14T15:41:58.8884089+01:00:Thread#0:T:warning: The previous FeatureContext was not disposed.
2019-10-14T15:41:58.8894173+01:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-10-14T15:41:58.8903977+01:00:Thread#0:B:Given I am on the bbc login page
2019-10-14T15:41:58.8954208+01:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-10-14T15:41:58.8963965+01:00:Thread#0:B:And I have entered a valid username
2019-10-14T15:41:58.8963965+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8963965+01:00:Thread#0:B:And I have entered a valid password
2019-10-14T15:41:58.8963965+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8963965+01:00:Thread#0:B:When I press login btn
2019-10-14T15:41:58.8973959+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8973959+01:00:Thread#0:B:Then I should see the user account homepage
2019-10-14T15:41:58.8973959+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.8983977+01:00:Thread#0:TestItem#5:Scheduler: reschedule tests for testitem #5
2019-10-14T15:41:58.8983977+01:00:Thread#0:Scheduler: get next test for thread 0
2019-10-14T15:41:58.8983977+01:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #5
2019-10-14T15:41:58.8983977+01:00:Thread#0:Scheduler: considering testitem #5 for thread 0
2019-10-14T15:41:58.8983977+01:00:Thread#0:TestItem#5:testItemMatchesCurrentTestThread:UnSpecific
2019-10-14T15:41:58.8983977+01:00:Thread#0:TestItem#5:runsOnOneOtherThreadSpecific:False
2019-10-14T15:41:58.8983977+01:00:Thread#0:TestItem#5:runsOnOneOtherThreadUnspecific:False
2019-10-14T15:41:58.8983977+01:00:Thread#0:Scheduler: using testitem #5 for thread 0
2019-10-14T15:41:58.8983977+01:00:Thread#0:Scheduler: Test #5 is scheduled for thread
2019-10-14T15:41:58.8983977+01:00:Thread#0:Scheduler: with testItemExecutionIndex 1
2019-10-14T15:41:58.9003981+01:00:Thread#0: Test #5/0 is finished on thread #0 as Failed within 0.0130027 seconds
2019-10-14T15:41:58.9003981+01:00:Thread#0: Test #5/1 is started on thread #0
2019-10-14T15:41:58.9003981+01:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-10-14T15:41:58.9003981+01:00:Thread#0:B:Given I am on the bbc login page
2019-10-14T15:41:58.9033972+01:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-10-14T15:41:58.9033972+01:00:Thread#0:B:And I have entered a valid username
2019-10-14T15:41:58.9033972+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9033972+01:00:Thread#0:B:And I have entered a valid password
2019-10-14T15:41:58.9043965+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9043965+01:00:Thread#0:B:When I press login btn
2019-10-14T15:41:58.9043965+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9053930+01:00:Thread#0:B:Then I should see the user account homepage
2019-10-14T15:41:58.9053930+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9053930+01:00:Thread#0:Scheduler: get next test for thread 0
2019-10-14T15:41:58.9053930+01:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #5
2019-10-14T15:41:58.9053930+01:00:Thread#0:Scheduler: considering testitem #5 for thread 0
2019-10-14T15:41:58.9053930+01:00:Thread#0:TestItem#5:testItemMatchesCurrentTestThread:UnSpecific
2019-10-14T15:41:58.9053930+01:00:Thread#0:TestItem#5:runsOnOneOtherThreadSpecific:False
2019-10-14T15:41:58.9053930+01:00:Thread#0:TestItem#5:runsOnOneOtherThreadUnspecific:False
2019-10-14T15:41:58.9053930+01:00:Thread#0:Scheduler: using testitem #5 for thread 0
2019-10-14T15:41:58.9053930+01:00:Thread#0:Scheduler: Test #5 is scheduled for thread
2019-10-14T15:41:58.9053930+01:00:Thread#0:Scheduler: with testItemExecutionIndex 2
2019-10-14T15:41:58.9074015+01:00:Thread#0: Test #5/1 is finished on thread #0 as Failed within 0.0070034 seconds
2019-10-14T15:41:58.9074015+01:00:Thread#0: Test #5/2 is started on thread #0
2019-10-14T15:41:58.9074015+01:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-10-14T15:41:58.9083945+01:00:Thread#0:B:Given I am on the bbc login page
2019-10-14T15:41:58.9104320+01:00:Thread#0:T:error: Object reference not set to an instance of an object.
2019-10-14T15:41:58.9104320+01:00:Thread#0:B:And I have entered a valid username
2019-10-14T15:41:58.9104320+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9104320+01:00:Thread#0:B:And I have entered a valid password
2019-10-14T15:41:58.9104320+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9104320+01:00:Thread#0:B:When I press login btn
2019-10-14T15:41:58.9104320+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9113945+01:00:Thread#0:B:Then I should see the user account homepage
2019-10-14T15:41:58.9113945+01:00:Thread#0:T:skipped because of previous errors
2019-10-14T15:41:58.9123961+01:00:Thread#0:Scheduler: get next test for thread 0
2019-10-14T15:41:58.9123961+01:00:Thread#:Scheduler: at the end of normal test queue
2019-10-14T15:41:58.9123961+01:00:Thread#0:Scheduler: enumerator for thread is at end
2019-10-14T15:41:58.9123961+01:00:Thread#0:Scheduler: No more tests for thread
2019-10-14T15:41:58.9163921+01:00:Thread#0: Test #5/2 is finished on thread #0 as Failed within 0.0089906 seconds
2019-10-14T15:41:58.9333936+01:00:Appdomain Disposed
2019-10-14T15:41:58.9363973+01:00:Trying to cancel thread
2019-10-14T15:41:58.9363973+01:00:Thread cancelled
2019-10-14T15:41:58.9454154+01:00:Thread#-1:Scheduler: get next test for thread -1
2019-10-14T15:41:58.9454154+01:00:Thread#:Scheduler: at the end of normal test queue
2019-10-14T15:41:58.9454154+01:00:Thread#-1:Scheduler: enumerator for thread is at end
2019-10-14T15:41:58.9533944+01:00;Thread#14;Info;test run finished
2019-10-14T15:41:58.9533944+01:00;Thread#14;Info;publishing test results
2019-10-14T15:41:58.9643992+01:00;Thread#14;Info;test results published
2019-10-14T15:41:58.9643992+01:00;Thread#14;Info;generating reports
2019-10-14T15:41:59.1163983+01:00;Thread#14;Info;Starting external report generation process
2019-10-14T15:42:01.7333958+01:00;Thread#14;Info;Successfully generated reports.
2019-10-14T15:42:01.7403991+01:00;Thread#14;Info;Successfully generated reports
2019-10-14T15:42:01.7553981+01:00:Total: 2 (test executions: 6)
2019-10-14T15:42:01.7584129+01:00:Succeeded: 0
2019-10-14T15:42:01.7593961+01:00:Ignored: 0
2019-10-14T15:42:01.7603952+01:00:Pending: 0
2019-10-14T15:42:01.7603952+01:00:Skipped: 0
2019-10-14T15:42:01.7613964+01:00:Failed: 2
2019-10-14T15:42:01.7753974+01:00;VSTestExecutionThread;Info;Adding attachments to VSTest
2019-10-14T15:42:01.7753974+01:00;VSTestExecutionThread;Info;adding Test Execution Report 'C:\Users\SSengamalam\source\repos\CSharpSpecFlowSelenium\TestResults\Unnamed project__2019-10-14T154142.html'
========== End of log file ==========
